### ISSUE TITLE
Lab 2 Review by Giuseppe Nicola Natalizio s305912

### ISSUE THREAD

**Issue by GNNatan** [SimoneBorella/computational-intelligence#1]
Hello there, Simone!
I liked the way you report is written, it's very detailed and easy to follow and the addition of graphs made your observations easy to understand.
The code is cleanly written and easy to understand, there's only one thing I noticed I'd like to point out.
The `generate_random_agent` function returns an individual with all the weights set to 0.5 rather than random, this means that when you initialise the population all the individuals have the same genome, this is partially compensated by the mutation, however, with such a low mutation chance we can expect  most of the population to have the same genome. I don't think this causes an issue in this particular problem, but in general it could lead to an inadequate exploration of the solution space.
I hope this review was useful to you and good luck on your next labs. 😊

**Comment by SimoneBorella** [comment]
Thank you for your review!
