### ISSUE TITLE
Lab 2 Review by Caretto Michelangelo s310178

### ISSUE THREAD

**Issue by rasenqt** [SimoneBorella/computational-intelligence#2]
Hello Simone, 
talking about rules,  I liked the way you splitted the two different choices :    
1-Which is the best row  for taking object?,
2-How many objects shall i take?
Thanks to this choice, we can explore more the Nim problem, and answer to a  question, can the choice of row and the number of object can be uncorrelate? And the answer  by looking at graph seems "Yes"   ,because you manage to reach almost 50% of winrate against the optimal solution, ....... but not everything is as it seems , cz with a more curiosity you would have notice that "optimal" function in reality is not that optimal.
So I very liked this different approch for the Nim games, and i liked too the way you implemented the GA algortihm, because all parameter are balanced up to me. 
I hope you'll enjoy this review and have fun playing CI.
Bye bye!

**Comment by SimoneBorella** [comment]
Thank you for your review!
